// <auto-generated />
using System;
using BM.Service.Core.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BM.Service.Core.Migrations
{
    [DbContext(typeof(SqlDBContext))]
    [Migration("20260720084909_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BM.Service.Core.Models.coinsLogEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("balance")
                        .HasColumnType("int");

                    b.Property<int>("change_amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("datetime2");

                    b.Property<int?>("source_id")
                        .HasColumnType("int");

                    b.Property<string>("source_type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex(new[] { "user_id", "create_time" }, "idx_user_time");

                    b.ToTable("coins_log");
                });

            modelBuilder.Entity("BM.Service.Core.Models.commentRecordEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("datetime2");

                    b.Property<byte>("rating")
                        .HasColumnType("tinyint");

                    b.Property<string>("reply_content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("reply_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("task_checkin_id")
                        .HasColumnType("int");

                    b.Property<int>("teacher_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex(new[] { "task_checkin_id" }, "idx_checkin");

                    b.ToTable("comment_record");
                });

            modelBuilder.Entity("BM.Service.Core.Models.dailyPlanEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("comment_count")
                        .HasColumnType("int");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("datetime2");

                    b.Property<int?>("day_no")
                        .HasColumnType("int");

                    b.Property<DateTime>("plan_date")
                        .HasColumnType("date");

                    b.Property<string>("progress")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("submit_time")
                        .HasColumnType("datetime2");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.Property<int?>("week_no")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex(new[] { "plan_date", "status" }, "idx_date_status");

                    b.HasIndex(new[] { "user_id", "plan_date" }, "uniq_user_date")
                        .IsUnique();

                    b.ToTable("daily_plan");
                });

            modelBuilder.Entity("BM.Service.Core.Models.taskCheckinEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("comment_id")
                        .HasColumnType("int");

                    b.Property<string>("comment_status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("datetime2");

                    b.Property<int>("daily_plan_id")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("image_urls")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("task_template_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("update_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("video_url")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("id");

                    b.HasIndex(new[] { "daily_plan_id" }, "idx_daily_plan");

                    b.ToTable("task_checkin");
                });

            modelBuilder.Entity("BM.Service.Core.Models.taskTemplateEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("icon_url")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("requirement")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("sort_order")
                        .HasColumnType("int");

                    b.Property<string>("teach_video_url")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("id");

                    b.ToTable("task_template");
                });

            modelBuilder.Entity("BM.Service.Core.Models.trainingPlanEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("day_no")
                        .HasColumnType("int");

                    b.Property<string>("task_ids")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("week_no")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex(new[] { "week_no", "day_no" }, "uniq_week_day")
                        .IsUnique();

                    b.ToTable("training_plan");
                });

            modelBuilder.Entity("BM.Service.Core.Models.userEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("archive_no")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("available_coins")
                        .HasColumnType("int");

                    b.Property<string>("avatar")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("last_login_ip")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<DateTime?>("last_login_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("nickname")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("password_hash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("total_coins")
                        .HasColumnType("int");

                    b.Property<string>("train_camp_status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.HasIndex(new[] { "archive_no" }, "uniq_archive_no")
                        .IsUnique()
                        .HasFilter("[archive_no] IS NOT NULL");

                    b.HasIndex(new[] { "phone" }, "uniq_phone")
                        .IsUnique()
                        .HasFilter("[phone] IS NOT NULL");

                    b.HasIndex(new[] { "username" }, "uniq_username")
                        .IsUnique();

                    b.ToTable("user");
                });

            modelBuilder.Entity("BM.Service.Core.Models.userRelationEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("create_time")
                        .HasColumnType("datetime2");

                    b.Property<int>("student_id")
                        .HasColumnType("int");

                    b.Property<int>("teacher_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex(new[] { "student_id" }, "idx_student");

                    b.HasIndex(new[] { "teacher_id", "student_id" }, "uniq_teacher_student")
                        .IsUnique();

                    b.ToTable("user_relation");
                });
#pragma warning restore 612, 618
        }
    }
}
